runtime: php73

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:uT+Kxsw1PZ5JsTNr8XBxOoA221QKLIFEP6VsUHau7YE=
  LOG_CHANNEL: stackdriver
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database

  DB_CONNECTION: mysql
  DB_DATABASE: negahdb
  DB_USERNAME: negah-admin
  DB_PASSWORD: negah.1234
  DB_SOCKET: "/cloudsql/YOUR_CONNECTION_NAME"

  PASSPORT_LOGIN_ENDPOINT:  ${APP_URL}/oauth/token
  PASSPORT_CLIENT_ID:  2
  PASSPORT_CLIENT_SECRET:  xSbNQERv4ePMAJQ0wD62dGOEqrk4WlDXmKayy0J1



