runtime: php73

env_variables:
  APP_NAME:Laravel
  APP_ENV:local
  APP_KEY:base64:4usUtzUSTtK4aSXhe6+5pXhuLJYd3aWzbSeC8ZJHdV0:
  APP_DEBUG:true
  APP_URL:https://sadiq.dev
  MIX_APP_URL:${APP_URL}
  
  LOG_CHANNEL: stackdriver
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database

  LOG_CHANNEL:stack

  DB_CONNECTION:mysql
  DB_HOST:127.0.0.1
  DB_PORT:3308
  DB_DATABASE:negahdb
  DB_USERNAME:negah-admin
  DB_PASSWORD:negah.1234
  DB_SOCKET: "/cloudsql/YOUR_CONNECTION_NAME"

  BROADCAST_DRIVER:log
  CACHE_DRIVER:file
  QUEUE_CONNECTION:sync
  SESSION_DRIVER:file
  SESSION_LIFETIME:120

  REDIS_HOST:127.0.0.1
  REDIS_PASSWORD:null
  REDIS_PORT:6379

  MAIL_MAILER:smtp
  MAIL_HOST:smtp.mailtrap.io
  MAIL_PORT:2525
  MAIL_USERNAME:null
  MAIL_PASSWORD:null
  MAIL_ENCRYPTION:null
  MAIL_FROM_ADDRESS:null
  MAIL_FROM_NAME:"${APP_NAME}"

  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:us-east-1
  AWS_BUCKET:

  PUSHER_APP_ID:
  PUSHER_APP_KEY:
  PUSHER_APP_SECRET:
  PUSHER_APP_CLUSTER:mt1

  MIX_PUSHER_APP_KEY:"${PUSHER_APP_KEY}"
  MIX_PUSHER_APP_CLUSTER:"${PUSHER_APP_CLUSTER}"


  PASSPORT_LOGIN_ENDPOINT: ${APP_URL}/oauth/token
  PASSPORT_CLIENT_ID: 2
  PASSPORT_CLIENT_SECRET: xSbNQERv4ePMAJQ0wD62dGOEqrk4WlDXmKayy0J1


  GITHUB_CLIENT_ID:fee3da13d3a61594c7fc
  GITHUB_CLIENT_SECRET:c0e552a0f65b814bd9c85b04ed3392f57b6354c6
  GITHUB_CALLBACK_URL:${APP_URL}/login/github/callback


  FACEBOOK_CLIENT_ID:633073854077014
  FACEBOOK_CLIENT_SECRET:0a7918ee24ba0906b5d5a85ed4557cf6
  FACEBOOK_CALLBACK_URL:${APP_URL}/login/facebook/callback

  GOOGLE_CLIENT_ID:238346087102-3aum0naolk3si4tvqlkbfcrti6iifp15.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET:JIdXXSj3ojIx4NiBjqsDCmMe
  GOOGLE_CALLBACK_URL:${APP_URL}/login/google/callback

  TWITTER_CLIENT_ID:zk2fkSVo9CNsWYz43JTjU1jjJ
  TWITTER_CLIENT_SECRET:1yyx8TAVc60epTf0BAPV827dGHGY4oCdeKuaxZMte8NdUdWmG1
  TWITTER_CALLBACK_URL:${APP_URL}/login/twitter/callback
