runtime: php73

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:4usUtzUSTtK4aSXhe6+5pXhuLJYd3aWzbSeC8ZJHdV0=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie