runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:dYQtUU3nftp5SuaTpXmj1Yfyj6Kph03TcbOPemtvbsA=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie