version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
        - "9000:80"
    volumes: 
        - ./:/var/www/html
        - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php
        - mysql
    networks:
        - laravel

  php:
    build: 
        context: .
        dockerfile: Dockerfile
    container_name: ${APP_NAME}_php
    volumes: 
        - ./:/var/www/app
    ports: 
        - "9000:80"
    networks:
        - laravel

  mysql:
    image: mysql:5.7.22
    container_name: ${APP_NAME}_mysql
    restart: unless-stopped
    tty: true
    ports: 
        - "3306:3306"
    volumes: 
        - ./:/var/lib/mysql
    environment: 
        MYSQL_DATABASE: negahdb
        MYSQL_USER: negah-admin
        MYSQL_PASSWORD: negah.1234
        MYSQL_ROOT_PASSWORD: negah.1234
        SERVICE_TAG: dev
        SERVICE_NAME: mysql
    networks:
        - laravel
  # cache:
  #   container_name: ${APP_NAME}_cache
  #   image: redis:4.0.11
  #   ports:
  #     - 63790:6379
  # search:
  #   container_name: ${APP_NAME}_search
  #   image: elasticsearch:6.4.1
  #   ports:
  #     - 6200:9200